### ISSUE TITLE
Add atomic `tryReadMVar`

### ISSUE THREAD

**Issue by crockeea** [ygale/strict-concurrency#2]
Control.Concurrent exports an atomic `tryReadMVar`, but strict-concurrency does not. When I switched from lazy MVars to strict MVars, I therefore had to write my own `tryReadMVar`, and not knowing much about the problems that can occur, wrote something that did not behave as I expected (i.e., it wasn't atomic). See https://stackoverflow.com/questions/54120390/readmvar-doesnt-wake-up-on-putmvar. 

It would be very useful to have a strict version of this function!

**Comment by ygale** [comment]
@crockeea Now that you've looked into to it, do you know how to do it? Wanna try your hand at a PR?

**Comment by treeowl** [comment]
The same race occurs in `readMVar`. I think this should just re-export the versions of both functions from `Control.Concurrent.MVar`.

**Comment by crockeea** [comment]
I do not know how to implement `readMVar` atomically; I just stopped using this library once I found the issue. Presumably, the Right Way to do this could be discovered by digging into the Control.Concurrent [source code](https://downloads.haskell.org/~ghc/8.4.2/docs/html/libraries/base-4.11.1.0/src/GHC.MVar.html#readMVar). It's not clear to me what's going on there, though.

**Comment by treeowl** [comment]
@crockeea, I'm quite confident the right thing to do is just to re-export the version from `Control.Concurrent.MVar`, which is (these days) a thin wrapper around an atomic primop.
